{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "8c044b42-be11-48f1-a94a-f060e2244a2b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: streamlit in c:\\users\\hemac\\anaconda3\\lib\\site-packages (1.45.1)\n",
      "Requirement already satisfied: pandas in c:\\users\\hemac\\anaconda3\\lib\\site-packages (2.2.3)\n",
      "Requirement already satisfied: numpy in c:\\users\\hemac\\anaconda3\\lib\\site-packages (2.2.0)\n",
      "Requirement already satisfied: plotly in c:\\users\\hemac\\anaconda3\\lib\\site-packages (6.3.1)\n",
      "Requirement already satisfied: seaborn in c:\\users\\hemac\\anaconda3\\lib\\site-packages (0.13.2)\n",
      "Requirement already satisfied: matplotlib in c:\\users\\hemac\\anaconda3\\lib\\site-packages (3.9.3)\n",
      "Requirement already satisfied: scikit-learn in c:\\users\\hemac\\anaconda3\\lib\\site-packages (1.6.0)\n",
      "Requirement already satisfied: altair<6,>=4.0 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from streamlit) (5.5.0)\n",
      "Requirement already satisfied: blinker<2,>=1.5.0 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from streamlit) (1.9.0)\n",
      "Requirement already satisfied: cachetools<6,>=4.0 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from streamlit) (5.5.1)\n",
      "Requirement already satisfied: click<9,>=7.0 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from streamlit) (8.1.8)\n",
      "Requirement already satisfied: packaging<25,>=20 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from streamlit) (24.2)\n",
      "Requirement already satisfied: pillow<12,>=7.1.0 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from streamlit) (11.1.0)\n",
      "Requirement already satisfied: protobuf<7,>=3.20 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from streamlit) (5.29.3)\n",
      "Requirement already satisfied: pyarrow>=7.0 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from streamlit) (19.0.0)\n",
      "Requirement already satisfied: requests<3,>=2.27 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from streamlit) (2.32.3)\n",
      "Requirement already satisfied: tenacity<10,>=8.1.0 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from streamlit) (9.0.0)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from streamlit) (4.15.0)\n",
      "Requirement already satisfied: watchdog<7,>=2.1.5 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from streamlit) (4.0.2)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from streamlit) (3.1.43)\n",
      "Requirement already satisfied: tornado<7,>=6.0.3 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from streamlit) (6.5.1)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from pandas) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (3.1.6)\n",
      "Requirement already satisfied: jsonschema>=3.0 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)\n",
      "Requirement already satisfied: narwhals>=1.14.2 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (1.31.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from click<9,>=7.0->streamlit) (0.4.6)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)\n",
      "Requirement already satisfied: smmap<5,>=3.0.1 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2.6.3)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2026.2.25)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from matplotlib) (1.3.1)\n",
      "Requirement already satisfied: cycler>=0.10 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from matplotlib) (0.11.0)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from matplotlib) (4.55.3)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from matplotlib) (1.4.8)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from matplotlib) (3.2.0)\n",
      "Requirement already satisfied: scipy>=1.6.0 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from scikit-learn) (1.15.3)\n",
      "Requirement already satisfied: joblib>=1.2.0 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from scikit-learn) (1.4.2)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from scikit-learn) (3.5.0)\n",
      "Requirement already satisfied: attrs>=22.2.0 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.3.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.22.3)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\hemac\\anaconda3\\lib\\site-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)\n"
     ]
    }
   ],
   "source": [
    "!pip install streamlit pandas numpy plotly seaborn matplotlib scikit-learn"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "04ff2a4e-b298-4a39-ac12-9d0b11bbe1bd",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly.express as px\n",
    "import plotly.graph_objects as go\n",
    "from sklearn.preprocessing import MinMaxScaler"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "05d7c7d8-c809-4f97-8fe2-dcce9c703f9c",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-05-19 12:56:51.248 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:56:51.249 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:56:51.250 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:56:51.251 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:56:51.252 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:56:51.253 No runtime found, using MemoryCacheStorageManager\n"
     ]
    }
   ],
   "source": [
    "st.set_page_config(\n",
    "    page_title=\"6G Smart Factory Dashboard\",\n",
    "    layout=\"wide\",\n",
    "    initial_sidebar_state=\"expanded\"\n",
    ")\n",
    "\n",
    "# --------------------------------------------------\n",
    "# TITLE\n",
    "# --------------------------------------------------\n",
    "\n",
    "st.title(\"🏭 Manufacturing Process Health and Operational Efficiency Dashboard\")\n",
    "st.markdown(\"### 6G-Enabled Smart Factory Analytics\")\n",
    "\n",
    "# --------------------------------------------------\n",
    "# LOAD DATA\n",
    "# --------------------------------------------------\n",
    "\n",
    "@st.cache_data\n",
    "def load_data():\n",
    "    df = pd.read_csv(\"Thales_Group_Manufacturing.csv\")\n",
    "    df.columns = df.columns.str.strip()\n",
    "\n",
    "    if \"Timestamp\" in df.columns:\n",
    "        df[\"Timestamp\"] = pd.to_datetime(df[\"Timestamp\"])\n",
    "    elif \"Date\" in df.columns and \"Time\" in df.columns:\n",
    "        df[\"Timestamp\"] = pd.to_datetime(\n",
    "            df[\"Date\"].astype(str) + \" \" + df[\"Time\"].astype(str)\n",
    "        )\n",
    "    elif \"Date\" in df.columns:\n",
    "        df[\"Timestamp\"] = pd.to_datetime(df[\"Date\"])\n",
    "    else:\n",
    "        raise KeyError(f\"No Date/Timestamp column found. Columns are: {df.columns.tolist()}\")\n",
    "\n",
    "    df[\"Hour\"] = df[\"Timestamp\"].dt.hour\n",
    "    df[\"Day\"] = df[\"Timestamp\"].dt.day\n",
    "    df[\"Month\"] = df[\"Timestamp\"].dt.month\n",
    "\n",
    "    return df\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "1c8b2fcc-7c4c-437c-86a1-9cdc945df4bb",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-05-19 12:57:46.779 No runtime found, using MemoryCacheStorageManager\n",
      "2026-05-19 12:57:46.780 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:46.781 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:46.782 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "C:\\Users\\hemac\\AppData\\Local\\Temp\\ipykernel_14160\\3593329482.py:24: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.\n",
      "  df[\"Timestamp\"] = pd.to_datetime(df[\"Timestamp\"])\n",
      "2026-05-19 12:57:47.301 Thread 'Thread-6': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:47.332 Thread 'Thread-6': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.550 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.551 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.552 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.553 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.556 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.557 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.559 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.561 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.562 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.572 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.573 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.575 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.576 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.577 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.582 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.583 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.585 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.586 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.587 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:57:49.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "df = load_data()\n",
    "st.sidebar.header(\"Dashboard Filters\")\n",
    "\n",
    "machine_filter = st.sidebar.multiselect(\n",
    "    \"Select Machine\",\n",
    "    options=df['Machine_ID'].unique(),\n",
    "    default=df['Machine_ID'].unique()\n",
    ")\n",
    "\n",
    "mode_filter = st.sidebar.multiselect(\n",
    "    \"Select Operation Mode\",\n",
    "    options=df['Operation_Mode'].unique(),\n",
    "    default=df['Operation_Mode'].unique()\n",
    ")\n",
    "\n",
    "start_date = st.sidebar.date_input(\n",
    "    \"Start Date\",\n",
    "    df['Timestamp'].min().date()\n",
    ")\n",
    "\n",
    "end_date = st.sidebar.date_input(\n",
    "    \"End Date\",\n",
    "    df['Timestamp'].max().date()\n",
    ")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "080f630d-6351-492a-8175-5865ed82ec61",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "filtered_df = df[\n",
    "    (df['Machine_ID'].isin(machine_filter)) &\n",
    "    (df['Operation_Mode'].isin(mode_filter)) &\n",
    "    (df['Timestamp'].dt.date >= start_date) &\n",
    "    (df['Timestamp'].dt.date <= end_date)\n",
    "]\n",
    "\n",
    "# --------------------------------------------------\n",
    "# MACHINE HEALTH INDEX\n",
    "# --------------------------------------------------\n",
    "\n",
    "health_features = filtered_df[[\n",
    "    'Temperature_C',\n",
    "    'Vibration_Hz',\n",
    "    'Power_Consumption_kW',\n",
    "    'Predictive_Maintenance_Score'\n",
    "]]\n",
    "\n",
    "scaler = MinMaxScaler()\n",
    "scaled = scaler.fit_transform(health_features)\n",
    "\n",
    "filtered_df['Machine_Health_Index'] = (\n",
    "    scaled[:,0] * 0.35 +\n",
    "    scaled[:,1] * 0.30 +\n",
    "    scaled[:,2] * 0.20 +\n",
    "    scaled[:,3] * 0.15\n",
    ")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "7b37b1d9-14fe-49f0-a36f-cb98989b5e01",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-05-19 12:58:46.907 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:58:46.908 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:58:46.909 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:58:46.910 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:58:46.910 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:58:46.911 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:58:46.912 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:58:46.912 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:58:46.915 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:58:46.916 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:58:46.918 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:58:46.918 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:58:46.920 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:58:46.921 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:58:46.923 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:58:46.924 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:58:46.925 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:58:46.926 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "st.subheader(\"📌 Factory Health Overview\")\n",
    "\n",
    "col1, col2, col3, col4, col5 = st.columns(5)\n",
    "\n",
    "with col1:\n",
    "    st.metric(\n",
    "        \"Total Machines\",\n",
    "        filtered_df['Machine_ID'].nunique()\n",
    "    )\n",
    "\n",
    "with col2:\n",
    "    st.metric(\n",
    "        \"Avg Temperature\",\n",
    "        round(filtered_df['Temperature_C'].mean(), 2)\n",
    "    )\n",
    "\n",
    "with col3:\n",
    "    st.metric(\n",
    "        \"Avg Production Speed\",\n",
    "        round(filtered_df['Production_Speed_units_per_hr'].mean(), 2)\n",
    "    )\n",
    "\n",
    "with col4:\n",
    "    st.metric(\n",
    "        \"Avg Defect Rate\",\n",
    "        round(filtered_df['Quality_Control_Defect_Rate_%'].mean(), 2)\n",
    "    )\n",
    "\n",
    "with col5:\n",
    "    st.metric(\n",
    "        \"Avg Error Rate\",\n",
    "        round(filtered_df['Error_Rate_%'].mean(), 2)\n",
    "    )\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "0603da3c-7cba-4b08-8564-0e35474bbfd9",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-05-19 12:59:12.415 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:59:12.416 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:59:12.635 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:59:12.636 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:59:12.638 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:59:12.639 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:59:12.640 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:59:12.641 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:59:12.717 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:59:12.718 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:59:12.719 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 12:59:12.721 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "st.subheader(\"⚙️ Efficiency Status Distribution\")\n",
    "\n",
    "fig_eff = px.pie(\n",
    "    filtered_df,\n",
    "    names='Efficiency_Status',\n",
    "    title='Efficiency Status Breakdown'\n",
    ")\n",
    "\n",
    "st.plotly_chart(fig_eff, use_container_width=True)\n",
    "\n",
    "# --------------------------------------------------\n",
    "# MACHINE HEALTH DASHBOARD\n",
    "# --------------------------------------------------\n",
    "\n",
    "st.subheader(\"🩺 Machine Health Dashboard\")\n",
    "\n",
    "health_machine = filtered_df.groupby('Machine_ID')[[\n",
    "    'Temperature_C',\n",
    "    'Vibration_Hz',\n",
    "    'Power_Consumption_kW',\n",
    "    'Machine_Health_Index'\n",
    "]].mean().reset_index()\n",
    "\n",
    "fig_health = px.bar(\n",
    "    health_machine,\n",
    "    x='Machine_ID',\n",
    "    y='Machine_Health_Index',\n",
    "    color='Machine_Health_Index',\n",
    "    title='Machine Health Index by Machine'\n",
    ")\n",
    "\n",
    "st.plotly_chart(fig_health, use_container_width=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "67983944-6f2e-47a0-a6f9-969ec458a056",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-05-19 13:01:26.446 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.447 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.566 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.568 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.576 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.578 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.837 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.840 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.849 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.851 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.853 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.853 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.855 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.856 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.856 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.910 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.911 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.914 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:26.915 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:27.005 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:27.006 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:27.012 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:27.013 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "st.subheader(\"Temperature Trend Analysis\")\n",
    "\n",
    "fig = px.scatter(\n",
    "    filtered_df,\n",
    "    x=\"Temperature_C\",\n",
    "    y=\"Quality_Control_Defect_Rate_%\",\n",
    "    color=\"Operation_Mode\",\n",
    "    size=\"Error_Rate_%\",\n",
    "    hover_data=[\"Machine_ID\"],\n",
    "    title=\"Temperature vs Defect Rate\"\n",
    ")\n",
    "\n",
    "st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "# --------------------------------------------------\n",
    "# ERROR RATE ANALYSIS\n",
    "# --------------------------------------------------\n",
    "\n",
    "st.subheader(\"🚨 Error Frequency Analysis\")\n",
    "\n",
    "fig_error = px.line(\n",
    "    filtered_df,\n",
    "    x='Timestamp',\n",
    "    y='Error_Rate_%',\n",
    "    color='Machine_ID',\n",
    "    title='Operational Error Rate Over Time'\n",
    ")\n",
    "\n",
    "st.plotly_chart(fig_error, use_container_width=True)\n",
    "\n",
    "# --------------------------------------------------\n",
    "# NETWORK PERFORMANCE\n",
    "# --------------------------------------------------\n",
    "\n",
    "st.subheader(\"📡 6G Network Diagnostics\")\n",
    "\n",
    "col_net1, col_net2 = st.columns(2)\n",
    "\n",
    "with col_net1:\n",
    "\n",
    "    fig_latency = px.histogram(\n",
    "        filtered_df,\n",
    "        x='Network_Latency_ms',\n",
    "        nbins=30,\n",
    "        title='Network Latency Distribution'\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(fig_latency, use_container_width=True)\n",
    "\n",
    "with col_net2:\n",
    "\n",
    "    fig_packet = px.scatter(\n",
    "        filtered_df,\n",
    "        x='Packet_Loss_%',\n",
    "        y='Error_Rate_%',\n",
    "        color='Operation_Mode',\n",
    "        title='Packet Loss vs Error Rate'\n",
    "    )\n",
    "\n",
    "    st.plotly_chart(fig_packet, use_container_width=True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "cac804de-6d19-40ce-a1e0-98122276b83e",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-05-19 13:01:52.852 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:52.853 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:52.957 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:52.959 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:52.967 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:52.969 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:52.970 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:52.971 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:52.988 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:52.989 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:52.990 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:52.991 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:54.029 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:54.030 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:54.031 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:54.031 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:54.032 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:01:54.033 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "False"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "st.subheader(\"⚡ Power Consumption vs Efficiency\")\n",
    "\n",
    "fig_power = px.scatter(\n",
    "    filtered_df,\n",
    "    x='Power_Consumption_kW',\n",
    "    y='Production_Speed_units_per_hr',\n",
    "    color='Efficiency_Status',\n",
    "    size='Machine_Health_Index',\n",
    "    hover_data=['Machine_ID'],\n",
    "    title='Power Consumption vs Production Speed'\n",
    ")\n",
    "\n",
    "st.plotly_chart(fig_power, use_container_width=True)\n",
    "\n",
    "# --------------------------------------------------\n",
    "# MACHINE COMPARISON TABLE\n",
    "# --------------------------------------------------\n",
    "\n",
    "st.subheader(\"📋 Machine Performance Summary\")\n",
    "\n",
    "summary = filtered_df.groupby('Machine_ID').agg({\n",
    "    'Temperature_C':'mean',\n",
    "    'Vibration_Hz':'mean',\n",
    "    'Power_Consumption_kW':'mean',\n",
    "    'Production_Speed_units_per_hr':'mean',\n",
    "    'Quality_Control_Defect_Rate_%':'mean',\n",
    "    'Error_Rate_%':'mean',\n",
    "    'Machine_Health_Index':'mean'\n",
    "}).round(2)\n",
    "\n",
    "st.dataframe(summary, use_container_width=True)\n",
    "\n",
    "# --------------------------------------------------\n",
    "# DOWNLOAD SECTION\n",
    "# --------------------------------------------------\n",
    "\n",
    "st.subheader(\"⬇️ Download Filtered Data\")\n",
    "\n",
    "csv = filtered_df.to_csv(index=False).encode('utf-8')\n",
    "\n",
    "st.download_button(\n",
    "    label=\"Download CSV\",\n",
    "    data=csv,\n",
    "    file_name='filtered_factory_data.csv',\n",
    "    mime='text/csv'\n",
    ")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "2a837597-4d22-4089-aa6b-ae1526201f6c",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-05-19 13:02:06.823 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:02:06.824 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:02:06.825 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:02:06.826 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:02:06.828 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-19 13:02:06.828 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "st.markdown(\"---\")\n",
    "st.markdown(\"### ✅ Smart Factory Operational Analytics System\")\n",
    "st.markdown(\"Developed using Streamlit + Plotly + Industrial IoT Analytics\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "140e406c-a590-4d09-9c4b-cbd5e7830880",
   "metadata": {},
   "outputs": [],
   "source": [
    "!streamlit run app.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "74b3c914-aec2-4544-b0a0-51d9625b1e96",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
